# Generated by Django 3.1.4 on 2020-12-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='scrore',
        ),
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
